ci: add zerotier vpn and database migration step (#14)
* feat: add zerotier ip address mapping in compose

* ci: setup zerotier vpn

* ci: add db migration step

* ci: add validate migration files step

* fix(ci): use cli directly for linting

* fix(ci): use elevated access gh token for checkout

* fix(ci): change git base to master when linting migrations

* fix(ci): change git base to master when linting migrations in pr workflow

* fix(ci): checkout multiple branches for git base lint

* fix(ci): change migration lint strategy to latest by changes

* fix(ci): get changed files list by prefix

diff --git a/.github/workflows/deploy-stg.yml b/.github/workflows/deploy-stg.yml
--- a/.github/workflows/deploy-stg.yml
+++ b/.github/workflows/deploy-stg.yml
@@ -5,6 +5,7 @@ env:
   CONFIG_DIR: infra/stg
   DEPLOY_DIR: sapungobrol
   ENV: ${{ secrets.STG_ENV }}
+  DATABASE_MIGRATE_URL: ${{ secrets.STG_DATABASE_MIGRATE_URL }}
   # VM variables
   HOST: ${{ vars.STG_SSH_HOST }}
   PORT: ${{ vars.STG_SSH_PORT }}
@@ -39,6 +40,8 @@ jobs:
     steps:
       - name: Checkout Sources
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Setup python
         uses: actions/setup-python@v5
@@ -51,8 +54,28 @@ jobs:
       - name: Setup coverage and pytest
         run: pip install coverage pytest
 
+      - name: Get list of changed migration files
+        id: migration-changes-list
+        uses: dorny/paths-filter@v3
+        with:
+          filters: |
+            changed:
+              - 'migrations/**'
+          list-files: json
+
+      - name: Get number of changed migration files
+        id: migration-changes
+        run: |
+          MIGRATION_CHANGES_LIST=${{ steps.migration-changes-list.outputs.changed_files }}
+          MIGRATION_CHANGES_COUNT=$(echo $MIGRATION_CHANGES_LIST | jq length)
+          echo "count=$MIGRATION_CHANGES_COUNT" >> "$GITHUB_OUTPUT"
+
       - name: Setup Atlas
         uses: ariga/setup-atlas@v0
+
+      - name: Lint migration files
+        if: ${{ steps.migration-changes.outputs.count > 0 }}
+        run: atlas migrate lint --dir file://migrations --dev-url postgres://postgres:postgres@localhost:5433/postgres?sslmode=disable --latest ${{ steps.migration-changes.outputs.count }}
 
       - name: Run migrations
         run: atlas migrate apply --url postgres://postgres:postgres@localhost:5433/postgres?sslmode=disable
@@ -109,6 +132,29 @@ jobs:
     needs: [build]
     runs-on: ubuntu-24.04
     steps:
+      - name: Connect to ZeroTier
+        uses: zerotier/github-action@v1.0.1
+        with:
+          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
+          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
+
+      - name: Ping ZeroTier host
+        shell: bash
+        run: |
+          count=60 # 1 minute
+          while ! ping -c 1 ${{ secrets.ZEROTIER_HOST_IP }} ; do
+            echo "Waiting..." ;
+            sleep 1 ;
+            let count=count-1
+          done
+
+          if [ $count -eq 0 ]; then
+            echo "Failed to ping host"
+            exit 1
+          fi
+
+          echo "Ping success!"
+
       - name: Checkout Sources
         uses: actions/checkout@v4
 
@@ -151,3 +197,6 @@ jobs:
       - name: Run containers based on docker compose
         run: |
           ssh ${{ env.HOST }} 'sudo bash -c "cd ${{ env.DEPLOY_DIR }}; docker compose pull; docker compose down; docker compose up -d"'
+
+      - name: Apply database migrations
+        run: atlas migrate apply --url ${{ env.DATABASE_MIGRATE_URL }}
